# ==========================================
# ДОСТУПЫ И API
# ==========================================
elevenlabs:
  api_key: "5566916825:324d556e4a664c4854344b6643744c6a7172527a53513d3d"
  voice_id: "ZthjuvLPty3kTMaNKVKb"       # ID голоса (по умолчанию Bella, замени на свой)
  model_id: "eleven_multilingual_v2"     # Модель v2 отлично говорит по-русски
  template_uuid: "20eefddc-b15a-498a-8c81-2fc941e66d22"

# ==========================================
# ПУТИ И ФАЙЛЫ
# ==========================================
paths:
  script_file: "input/script_export.txt"        # Тот самый файл с разметкой "ГЛАВА - 1..."
  input_images: "input/images/"          # Отсюда скрипт будет брать [1.jpg]
  input_voice: "input/voice/"            # Сюда скрипт будет скачивать mp3 от ElevenLabs
  input_video: "input/video/"
  assets_dir: "assets/"
  output_dir: "output/"
  template_dir: "template/"

filenames:
  bg_audio: "veter.mp3"

# ==========================================
# НАСТРОЙКИ ВИДЕО И АУДИО
# ==========================================
audio:
  voice_volume: 1.0
  bgm_volume: 0.50

video:
  padding_start: 0.3      # Пауза перед первым кадром главы
  padding_end: 1.0        # Пауза в конце главы